** Solution de l'exercice 15

    Pour chacune des situations suivantes, indiquons comment la
    résoudre selon la représentation vectorielle parmi :
    
    + Analytique (coordonnées, calculs algébriques)
    + Colinéarité (proportionnalité, déterminant)
    + Géométrique (relation de Chasles, parallélogramme)


    1. Démontrer que les points A, B, C sont alignés.
       + Analytique : à l'aide des coordonnées de chaque point on peut
         calculer les coordonnées des vecteurs \(\overrightarrow{AB}\)
         et \(\overrightarrow{AC}\) et vérifier si les vecteurs sont
         colinéaires ou pas.
       + Colinéarité : à l'aide des coordonnées ou de la décomposition
         de Chasles on peut calculer le déterminant ou établir une
         relation du type \(\overrightarrow{AB} =
         k\overrightarrow{AC}\) si les vecteurs sont colinéaires.
       + Géométrique : la relation de Chasles nous permet d'établie si
         la relation \(\overrightarrow{AB} = k\overrightarrow{AC}\)
         existe ou pas
    2. Calculer la distance entre deux points A(2;3) et B(5;7)
       + Analytique : on applique la formule (qui découle de
         Pythagore)
       + Colinéarité : pour ce type de problème la colinéarité est
         inutile
       + Géométrique : pour ce type de problème ni Chasles ni les
         identités du parallélogramme ne peuvent servir
    3. Montrer que ABCD est un parallélogramme
       + Analytique : à l'aide des coordonnées on peut vérifier si on
         a l'égalité vectorielle
	 \[\overrightarrow{AB} = \overrightarrow{DC}\]
	 ou pas.
       + Colinéarité : à l'aide des coordonnées ou de la relation de
         Chasles on peut vérifier si on a l'égalité vectorielle
	 \[\overrightarrow{AB} = \overrightarrow{DC}\]
	 ou pas. On peut également calculer les deux déterminants
         importants
	 \[det(\overrightarrow{AB} , \overrightarrow{DC})\quad
         det(\overrightarrow{AD} , \overrightarrow{BC})\]
       + Géométrique : en utilisant Chasles on peut vérifier si on
         obtient la relation
	 \[\overrightarrow{AB} + \overrightarrow{AD} = \overrightarrow{AC}\]
    4. Trouver les coordonnées du point M tel que :
       \[\overrightarrow{AM} = 2\overrightarrow{AB} +
       3\overrightarrow{AC}\]
       + Analytique : on calcule les coordonnées des vecteurs \(\overrightarrow{AB}\)
         et \(\overrightarrow{AC}\) et on résout les deux équations
         pour obtenir les coordonnées du points M(x ; y).
	 Concrètement :
	 \begin{align*}
         x - x_A &= 2(x_B - x_A) + 3(x_C - x_A)\\
         y - y_A &= 2(y_B - y_A) + 3(y_C - y_A)\\
         x &= -4x_A + 2x_B + 3x_C\\
         y &= -4y_A + 2y_B + 3y_C
	 \end{align*}
       + Colinéarité : on ne peut pas obtenir les coordonnées du point
         M uniquement avec le déterminant.
       + Géométrique : on peut construire le point M grâce à la
         relation vectorielle puis en utilisant Chasles on peut
         exprimer le vecteur \(\overrightarrow{OM}\) en fonction des
         vecteurs \(\overrightarrow{OA}\), \(\overrightarrow{OB}\) et
         \(\overrightarrow{OC}\)
    5. Vérifier si deux droites (AB) et (CD) sont parallèles
       + Analytique : on peut comparer les coordonnées des vecteurs
         \(\overrightarrow{AB}\) et \(\overrightarrow{CD}\)
       + Colinéarité : on peut calculer le déterminant
         \(det(\overrightarrow{AB} , \overrightarrow{CD})\) et voir
         s'il est nul ou pas
       + Géométrique : on peut vérifier si on obtient une identité du
         parallélogramme ou pas


** Solution du programme

    Écrire un programme Python qui résout le problème
    \[\overrightarrow{AM} = a\overrightarrow{AB} +
    b\overrightarrow{AC}\]
    C'est-à-dire un programme qui permet d'exprimer les coordonnées du
    point M en fonction des paramètres a et b et des coordonnées des
    points déjà existants A, B, et C.

    #+BEGIN_SRC python
      def get_M(a, b, A, B, C):
	  """
	  Cette fonction prend en entrées :
	  + a : 1 float correspondant au coefficient du vecteur AB
	  + b : 1 float correspondant au coefficient du vecteur AC
	  + A : 1 tuple de float correspondant aux coordonnées du point A
	  + B : 1 tuple de float correspondant aux coordonnées du point B
	  + C : 1 tuple de float correspondant aux coordonnées du point C
	  et elle renvoie 1 tuple de float correspondant aux coordonnées du point M
	  """
	  x = (1 - a - b) * A[0] + a * B[0] + b * C[0]
	  y = (1 - a - b) * A[1] + a * B[1] + b * C[1]
	  return (x, y)


      def vectAB(A, B):
	  """
	  Cette fonction prend en entrées :
	  + A : 1 tuple de float correspondant aux coordonnées du point A
	  + B : 1 tuple de float correspondant aux coordonnées du point B
	  et renvoie 1 tuple de float correspondant aux coordonnées du vecteur AB
	  """
	  x = B[0] - A[0]
	  y = B[1] - A[1]
	  return (x, y)


      # Tests
      a, b, A, B, C = 1, 1, (3, 2), (-3, 2), (3, -2)
      M = get_M(a, b, A, B, C)
      relation = f"On a la relation Vect(A, M) = {a}Vect(A, B) + {b}Vect(A, C)"
      print(relation)
      input("Pour voir les coordonnées du point M tapez 1\t")
      coordM = f"Voici les coordonnées du point M({M[0]}, {M[1]})"
      print(coordM)
      coordAB = vectAB(A, B)
      coordAC = vectAB(A, B = C)
      eqX = f"x - {A[0]} = {a} * {coordAB[0]} + {b} * {coordAC[0]}"
      input("Pour voir l'équation en x tapez 1\t")
      print(eqX)
      eqY = f"y - {A[1]} = {a} * {coordAB[1]} + {b} * {coordAC[1]}"
      input("Pour voir l'équation en y tapez 1\t")
      print(eqY)
      solve_x = f"x = {A[0] + a * coordAB[0] + b * coordAC[0]}"
      input("Pour voir la solution de l'équation en x tapez 1\t")
      print(solve_x)
      solve_y = f"y = {A[1] + a * coordAB[1] + b * coordAC[1]}"
      input("Pour voir la solution de l'équation en y tapez 1\t")
      print(solve_y)
    #+END_SRC


** Solution du QCM d'auto-évaluation 

    *Parmi les réponses proposées au moins une est la bonne. Cela
    signifie qu'il peut y avoir /plusieurs/ bonnes réponses.*
    
    1. Si ABC est un triangle et que D est un 4ème point qui vérifie
       l'égalité \[\overrightarrow{AD} = \overrightarrow{AB} +
       \overrightarrow{AC}\]
       alors on peut en déduire que :
       #+ATTR_LATEX: :options [label=\alph*.]
       1. \(\overrightarrow{AB} + \overrightarrow{BC} =
          \overrightarrow{AC}\) la relation de Chasles n'est pas une
          déduction, elle existe toujours
       2. ABCD est un parallélogramme 
       3. ABDC est un parallélogramme

	  (*Bonne réponse*)
       4. \(\overrightarrow{AB} = \overrightarrow{CD}\) et
          \(\overrightarrow{AC} = \overrightarrow{BD}\) les deux
          égalités sont vraies

	  (*Bonne réponse*)
       5. \(\overrightarrow{AB} = \overrightarrow{CD}\) ou
          \(\overrightarrow{AC} = \overrightarrow{BD}\)	une seule des
          deux égalités est vraie
       6. \(\overrightarrow{AB} \neq \overrightarrow{CD}\) et
          \(\overrightarrow{AC} \neq \overrightarrow{BD}\) aucune
          des égalités n'est vraie
       7. le point D est à l'intérieur du triangle ABC
       8. le point D est l'image du point A par la symétrie de
          centre le milieu du segment [BC]

	  (*Bonne réponse*)
       9. le point D est à l'extérieur du triangle ABC

	  (*Bonne réponse*)
       10. le point D est l'image du point I par la translation de
           vecteur \(\overrightarrow{AI}\) où I est le milieu du
           segment [BC]

	   (*Bonne réponse*)
    2. Si ABCD est un carré alors : 
       #+ATTR_LATEX: :options [label=\alph*.]
       1. Les vecteurs \(\overrightarrow{AB}\) et
          \(\overrightarrow{AC}\) forment une base orthornomée
       2. Les vecteurs \(\overrightarrow{AB}\) et
          \(\overrightarrow{AD}\) forment une base orthornomée

	  (*Bonne réponse*) 
       3. \(det(\overrightarrow{AB} , \overrightarrow{AC}) = 1\)	  
       4. \(det(\overrightarrow{AB} , \overrightarrow{AD}) = 0\)
       5. \(det(\overrightarrow{AB} , \overrightarrow{AD}) = 1\)
       6. \(det(\overrightarrow{AB} , \overrightarrow{AC}) = 0\)
       7. \(AC^2 = AB^2 + BC^2\)

	  (*Bonne réponse*)
       8. \(\overrightarrow{AB} + \overrightarrow{CD} =
          2\overrightarrow{AB}\)
       9. \(\overrightarrow{AB} + \overrightarrow{CD} = \vec{0}\)

	  (*Bonne réponse*)	  	  	 
       10. Le centre O du carré vérifie
	   \[\overrightarrow{OA} + \overrightarrow{OB} +
           \overrightarrow{OC} + \overrightarrow{OD} = \vec{0}\]

	   (*Bonne réponse*)	 
    3. Si ABCD est un rectangle et O l'intersection des droites (AC)
       et (BD) alors : 
       #+ATTR_LATEX: :options [label=\alph*.]
       1. \(\overrightarrow{OA} + \overrightarrow{OB} +
          \overrightarrow{OB} + \overrightarrow{OD} = \vec{0}\)

	  (*Bonne réponse*)
       2. \(\overrightarrow{AO} = \overrightarrow{OC} =
          \dfrac{1}{2}\overrightarrow{AC}\)

	  (*Bonne réponse*)
       3. \(det(\overrightarrow{AB} , \overrightarrow{AC}) = 1\)	  
       4. \(det(\overrightarrow{AB} , \overrightarrow{AD}) = 0\)
       5. \(det(\overrightarrow{AB} , \overrightarrow{AD}) = 1\)
       6. \(det(\overrightarrow{AB} , \overrightarrow{AC}) = 0\)
       7. \(AC > AB + BC\)
       8. \(AC < AB + AD\)

	  (*Bonne réponse*)
       9. \(AC = BD\)

	  (*Bonne réponse*)
       10. \(AC\neq BD\)	  	  	  	  	  
    4. Soient A et B deux points distincts du plan. Si C est l'image
       de B par la translation de vecteur \(\overrightarrow{AB}\)
       alors : 	 
       #+ATTR_LATEX: :options [label=\alph*.]
       1. B est le milieu du segment [AC]

	  (*Bonne réponse*)
       2. \(\overrightarrow{AC} = 2\overrightarrow{AB}\) 
       3. \(\overrightarrow{OC} = \overrightarrow{OA} +
          2\overrightarrow{OB}\)
       4. les coordonnées de C vérifient :
	  \begin{align*}
          x_C &= 2x_B - x_A\\
          y_C &= 2y_B - y_A
	  \end{align*}
       5. les coordonnées de C vérifient :
	  \begin{align*}
          x_C &= 2x_B + x_A\\
          y_C &= 2y_B + y_A
	  \end{align*}

	  (*Bonne réponse*)
       6. C est l'image de A par la symétrie de centre B.

	  (*Bonne réponse*)
       7. C est le milieu du segment [AB].
       8. \(\overrightarrow{AB} = \overrightarrow{BC}\)

	  (*Bonne réponse*)
       9. \(\overrightarrow{AB} + \overrightarrow{BC} =
          2\overrightarrow{AB}\)

	  (*Bonne réponse*)
       10. \(det(\overrightarrow{AB} , \overrightarrow{AC}) = 0\)

	   (*Bonne réponse*)
    5. Si on a \(det(\overrightarrow{AB}, \overrightarrow{AD}) \neq 0\)
       et \(det(\overrightarrow{AB}, \overrightarrow{DC}) = 0\) alors :
       #+ATTR_LATEX: :options [label=\alph*.]
       1. ABCD ou ABDC est un trapèze.

	  (*Bonne réponse*)
       2. Si AB = DC alors ABCD ou ABDC est un parallélogramme.

	  (*Bonne réponse*)
       3. Si AB = AD = DC alors ABCD est un losange.

	  (*Bonne réponse*)
       4. Si AB = AC = CD alors ABDC est un losange.

	  (*Bonne réponse*)
       5. Si AB = DC et CA = BD alors ABDC est un rectangle.
       6. Si AB = DC et AD = BC alors ABDC est un rectangle.
       7. Si AB = DC et AC = BD alors ABCD est un rectangle.

	  (*Bonne réponse*)
       8. Si AB = DC et AD = BC alors ABCD est un rectangle.
       9. Si AB = DC et AC = BD alors ABCD est un losange.
       10. Si AB = DC et AD = BC alors ABCD est un losange.

	   (*Bonne réponse*)
    6. Soient \(\vec{u}\), \(\vec{v}\) et \(\vec{w}\) trois vecteurs
       tels que \(\vec{w} = \vec{u} + \vec{v}\).
       #+ATTR_LATEX: :options [label=\alph*.]
       1. Si \(\lvert\lvert\vec{u}\rvert\rvert +
          \lvert\lvert\vec{v}\rvert\rvert =
          \lvert\lvert\vec{w}\rvert\rvert\) alors les trois vecteurs
          sont colinéaires.
       2. Il est impossible que les trois vecteurs soient colinéaires.
       3. Si \(det(\vec{u}, \vec{v}) = 0\) alors les trois vecteurs
          sont colinéaires.
       4. Si \(det(\vec{u}, \vec{v}) = 0\) alors \(det(\vec{v},
          \vec{w}) = 0\).
       5. Si \(det(\vec{w}, \vec{u}) = 0\) alors \(det(\vec{u},
          \vec{v}) = 0\).
       6. \(\lvert\lvert\vec{u}\rvert\rvert +
          \lvert\lvert\vec{v}\rvert\rvert >
          \lvert\lvert\vec{w}\rvert\rvert\)
       7. \(\lvert\lvert\vec{u}\rvert\rvert +
          \lvert\lvert\vec{v}\rvert\rvert <
          \lvert\lvert\vec{w}\rvert\rvert\)
       8. Si \(det(\vec{u}, \vec{v}) = 0\) alors soit \(\vec{u} =
          \vec{0}\) soit \(\vec{v} = \vec{0}\)
       9. Si \(det(\vec{u}, \vec{v}) = 0\) alors soit \(\vec{w} =
          \vec{u}\) soit \(\vec{w} = \vec{v}\)
       10. Si \(det(\vec{w}, \vec{u}) = 0\) alors soit \(\vec{u} =
          -\vec{v}\) soit \(\vec{w} = \vec{0}\)
    7. Soit un vecteur \(\vec{u}\) de norme
       \(\lvert\lvert\vec{u}\rvert\rvert = 5\).
       #+ATTR_LATEX: :options [label=\alph*.]
       1. Si \(x_{\vec{u}} = 3\) alors \(y_{\vec{u}} = 4\).
       2. Si \(x_{\vec{u}} = 3\) alors \(y_{\vec{u}} = -4\).	  
       3. Si \(x_{\vec{u}} = -3\) alors \(y_{\vec{u}} = -4\).
       4. Si \(x_{\vec{u}} = -3\) alors \(y_{\vec{u}} = 4\).
       5. Si \(x_{\vec{u}} = \pm 3\) alors \(y_{\vec{u}} = \pm 4\).

	  (*Bonne réponse*)
       6. Si \(x_{\vec{u}} = -4\) alors \(y_{\vec{u}} = 3\).
       7. Si \(x_{\vec{u}} = -4\) alors \(y_{\vec{u}} = -3\).	  
       8. Si \(x_{\vec{u}} = 4\) alors \(y_{\vec{u}} = -3\).
       9. Si \(x_{\vec{u}} = 4\) alors \(y_{\vec{u}} = 3\).
       10. Si \(x_{\vec{u}} = \pm 4\) alors \(y_{\vec{u}} = \pm 3\).

	   (*Bonne réponse*)
    8. Dans un repère orthonormée \((O ; \vec{i} , \vec{j})\) on
       considère les points A(3 ; 2), B(3 ; -2), C(-3 ; -2), D(3 ;
       -1), E(-3 ; -1), F(-1 ; -1), G(1 ; 1), H(1 ; 2), I(-1 ; 2).       
       #+ATTR_LATEX: :options [label=\alph*.]
       1. Les vecteurs \(\overrightarrow{AB}\) et
          \(\overrightarrow{AC}\) sont colinéaires car
          \[det(\overrightarrow{AB} , \overrightarrow{AC}) = 0\]
       2. Les vecteurs \(\overrightarrow{AH}\) et
          \(\overrightarrow{AI}\) sont colinéaires car
          \[det(\overrightarrow{AH} , \overrightarrow{AI}) = 0\]
       3. Les points A, B et C sont alignés.
       4. Les points D, E et F sont alignés.

	  (*Bonne réponse*)
       5. ABC est un triangle rectangle en B.

	  (*Bonne réponse*)
       6. ABD est un triangle rectangle en B.
       7. GDF est un triangle rectangle en G.

	  (*Bonne réponse*)
       8. GDF est un triangle isocèle en G.

	  (*Bonne réponse*)
       9. BCHA est un trapèze.

	  (*Bonne réponse*)
       10. Les vecteurs \(\overrightarrow{BC}\) et
           \(\overrightarrow{AH}\) sont colinéaires.

	   (*Bonne réponse*)
    9. Dans un repère orthonormée \((O ; \vec{i} , \vec{j})\) on
       considère les points A(2 ; 3), B(-3 ; 2), C(-2 ; -3); D(3 ;
       -2).
       #+ATTR_LATEX: :options [label=\alph*.]
       1. Le triangle BOA est isocèle en A.
       2. Le triangle BOA est isocèle en B.
       3. Le triangle BOA est isocèle en O.

	  (*Bonne réponse*)
       4. Le triangle BOA est rectangle en A.
       5. Le triangle BOA est rectangle en B.
       6. Le triangle BOA est rectangle en O.

	  (*Bonne réponse*)
       7. C est l'image de O par la translation de vecteur
          \(\overrightarrow{AO}\).

	  (*Bonne réponse*)
       8. D est l'image de O par la translation de vecteur
          \(\overrightarrow{BO}\).

	  (*Bonne réponse*)
       9. ABDC est un carré.
       10. ABCD est un carré.

	   (*Bonne réponse*)
